### ISSUE TITLE
Django 1.7 migrations require new functionality of adapters

### ISSUE THREAD

**Issue by freyley** [FoundationDB/sql-layer-adapter-django#4]
Using Django 1.7 with fdbsql results in this error:

    raise NotImplementedError('subclasses of BaseDatabaseWrapper may require a schema_editor() method')

This seems to be similar to the issues MySQL and other adapters had during Django 1.7's beta period:

http://bugs.mysql.com/bug.php?id=72542

**Comment by vlad-dragos** [comment]
@nathanlws Is there any way we can help? Did you start working on it?

**Comment by nathanlws** [comment]
I have a branch in progress for 1.7 support. Still running all the various tests but it will probably be ready by the end of the week.

Will definitely update this issue when it is done.

**Comment by nathanlws** [comment]
The new version (1.2.0) is now in PyPI and includes support for Django 1.7.
