### ISSUE TITLE
Transaction Issues with Django <=1.5 (past_version errors)

### ISSUE THREAD

**Issue by lylepratt** [FoundationDB/sql-layer-adapter-django#5]
# Background Info
[FoundationDB Community Forums](http://community.foundationdb.com/questions/42694/django-and-past-version-issues.html#comment-42706)

We successfully imported our data from MySQL into a FoundationDB test instance. I followed the instructions to get my dev environment set up to test our Django app, but I'm running into quite a few strange errors. Most seem to revolve around: DatabaseError: past_version issues.

I even created a new database and then ran syncdb but still got this same error. I'm using the PIP version of the Django sql layer adapter with the latest Django 1.5.

Running queries directly via `fdbsqlcli` seems to work. After running some queries via the CLI, I found that none of our data in our accounts table got imported. That explains some of the issues I'm seeing trying to run the dev environment on the imported data, but it does not explain ALL of the issues.

Example:
When I run `Account.objects.all()` in the Django console, I get:

```
    DatabaseError: FoundationDB transaction open too long: 1007 - past_version
```

When I run the same query via the CLI, it executes (returns no rows because the table is empty). There is NO data in that table. The transaction definitely did not run 5 secs. Why is it returning that error? Also, why is syncdb returning that same error?

There is also some seemly strange stuff with the `fdbcli --exec status` command. Here are the results of the `Workload`:

```
    Workload:
      Read rate              - 10 Hz
      Write rate             - 0 Hz
      Transactions started   - 6 Hz
      Transactions committed - 1 Hz
      Conflict rate          - 0 Hz
```

I'm currently doing NOTHING with the database (dev server not even running), so why does `Transactions started` and `Transactions committed` have those values?

# Recent Update

@nathanlws mentioned in the FoundationDB Community forums that there must be an issue with Django 1.5 leaving the transaction open. The default transaction functionality was changed in Django 1.6. "The adapter does pass all of the 1.5.12 tests. The test suite wraps each cases in a transaction, though, which is apparently why this [issue] doesn't show up."

**Comment by lylepratt** [comment]
**Update:**

I believe @nathanlws is going to add a notice in the documentation about this issue and nothing can be done to alleviate it for now. I'm closing this out.

**Comment by nathanlws** [comment]
@lylepratt Would you want to double check the new wording added in #6? Do you think that would have been enough to alert you before you started?

**Comment by lylepratt** [comment]
@nathanlws yep looks good. thanks!
