### ISSUE TITLE
Unique on text and char fields not supported

### ISSUE THREAD

**Issue by freyley** [FoundationDB/sql-layer-adapter-django#7]
When attempting to run syncdb with the fdbsql adapter for an existing project, I get this:

django.db.utils.OperationalError: Table `mysample`.`core_user` index `username` has unsupported type `LONGTEXT` from column `username`

This is whether the field is TextField(unique=True), or CharField(max_length=255, unique=True)

**Comment by freyley** [comment]
I'm not sure what's going on here, and I'd be totally willing to write a test case for this if I could. I cloned the repo and read the test documentation, and am a little stymied. I should have a copy of Django and apply these changes so that I can run the Django tests and they'll run against fdb? Seems odd. I would assume that unique=True on text fields functionality is tested in Django - should I go looking for that test somewhere?

**Comment by nathanlws** [comment]
`TextField` maps to `CLOB`. This is consistent with other adapters. SQL Layer does not currently support indexes on `CLOB` and won't for at least the next couple of releases.

`CharField` maps to `VARCHAR`, which supports unique as expected. I'm unable to reproduce the error with a simple model. Could you give an example of one that has troubling syncing?

> I should have a copy of Django and apply these changes so that I can run the Django tests and they'll run against fdb?

To run the stock Django tests you'll need to have the Django source checked out. There are a few manual steps at the moment but they should all be covered in the RUNNING_UNIT_TESTS.rst file.

> I would assume that unique=True on text fields functionality is tested in Django - should I go looking for that test somewhere?

There are a number of tests with models having CharField and unique=True. A quick check looks like the lengths range from 4 to 255.

**Comment by freyley** [comment]
Whoops, I believe you're right. I just didn't do enough migration deletion
and recreation. Thanks!

It's unfortunate, however, that it's effectively not possible to make
unique fields longer than 255 characters.

Thanks!

**Comment by nathanlws** [comment]
> It's unfortunate, however, that it's effectively not possible to make unique fields longer than 255 characters

Unique being restricted to 255 is a restriction that is only present in the MySQL adapter.

SQL Layer has no preset limit. In practice it will be only be limited by the data in use as the backing index will only support ~2K bytes for the key currently. This is roughly true for other adapters as well.
